### ISSUE TITLE
Add support for key-sanity mode

### ISSUE THREAD

**Issue by powerlord** [crossproduct42/alttprandohelper#16]
This is more of an idea rather than a bug.

Key-sanity was introduced in Randomizer v8.27.  Key-sanity removes keys, big keys, maps, and compasses from chests (but not pots or enemies) and mixes them into the Randomizer pools.  The sole exception (as far as I can tell) is a single key in south-west Skull Woods to prevent you from having to Save & Quit if you don't have the mirror.

Edit: This means that these items may be found in the Overworld or in a different dungeon.

However, this itself creates a problem for the tracker as it changes the number of chests available in each dungeon as well as changes when you can enter each dungeon. Some dungeons have no external keys (Eastern Palace), while others have a ton of them (Palace of Darkness).  Swamp Palace is especially annoying as you can't get past the first room without a key.

I may try to add this myself at some point, but I'm still gathering information, such as how many chests are in each dungeon and how many external keys are required to complete said dungeon.

**Comment by RebelusQuo** [comment]
This is a concept we are currently working on implementing for the tracker. Stay tuned for a new release.

**Comment by drseilzug** [comment]
there is a fork of this with key sanity support now.
https://github.com/wolfman2000/stumpy

**Comment by RebelusQuo** [comment]
I have finally finished implementing keysanity, provided as a pull request.

@drseilzug The implementation in that fork is based on AngularJs which, besides being AngularJs... , would not be compatible with the way we have now developed the code, which is in the direction of ReactJs.

With this I'll go ahead and close this issue.
