### ISSUE TITLE
Black screen when opening tracker

### ISSUE THREAD

**Issue by Dune-jr** [crossproduct42/alttprandohelper#17]
Chrome's console gives

![image](https://user-images.githubusercontent.com/355114/35092128-bb1ed8e2-fc3e-11e7-8a23-57ac4b4c6aa0.png)

**Comment by RebelusQuo** [comment]
This error is not from the 5.0.0 release, is it? in what commit does this show up?

**Comment by Dune-jr** [comment]
Sorry, should have given the version. The error is from the trunk version, the most recent from this git.

edit: I haven't tried disabling all extensions, will do that asap
edit2: No extension doesn't help, Firefox doesn't work either
edit3: should have mentionned 5.0.0 works just fine :)

**Comment by RebelusQuo** [comment]
Give me the sha hash please, it is always the most exact way to convey a specific commit because the master branch (which I assume is what you mean) changes as commits gets added.

**Comment by RebelusQuo** [comment]
Feel free to reopen the issue when you have the time to get back to us with the specific commit hash.

**Comment by Dune-jr** [comment]
Commit hash is fdc7a2c8a30f79c2d5180286210107cf64f6fbcd

**Comment by RebelusQuo** [comment]
Thank you. Fixed at commit c90ee019bf36ace314d675c08df53d014804d56d
