### ISSUE TITLE
readme.txt uses UNIX-style line endings

### ISSUE THREAD

**Issue by Dune-jr** [crossproduct42/alttprandohelper#18]
Double clicking on that file on Windows shows a file with no line endings. I think this should be changed.

**Comment by RebelusQuo** [comment]
This comes about from how github handles releases. The source code zip/tar.gz pulls files directly from the repo where files are stored with unix line endings (as they should). I will update the release with a zip "binary" which have windows endings later during the day.

Thank you for your report.

**Comment by Dune-jr** [comment]
Oh, didn't know, thanks for the explanation.
It seems a bit restricting that github insists on transforming text files into UNIX line endings to version control them.
I wonder what the correct way of including a Windows-compatible README.
I guess your solution is the right one, they need to be in the releases.

**Comment by RebelusQuo** [comment]
You *can* have files on the github repo with windows endings, but the norm is to have them on the repo in the canonical form, and git originating from linux, that form is unix endings. As a dev on windows you then configure your local git to translate the line endings from/to your local copy.

Both me and cross had not made an actual official release on github before, but we'll be sure to add a binary from now on.
