### ISSUE TITLE
Lake Hylia island is possible through swimming+mirroring but doesn't show up as available

### ISSUE THREAD

**Issue by Dune-jr** [crossproduct42/alttprandohelper#19]
![image](https://user-images.githubusercontent.com/355114/35097735-a7429c74-fc51-11e7-967f-74d9da1a1731.png)

**Comment by RebelusQuo** [comment]
How? Is this from a real run? Since you don't have the moonpearl you wouldn't be able to use hammer or hookshot to get to the lake from pyramid, and you can't swim either. There is no way to reach the DW side of the lake island.

**Comment by RebelusQuo** [comment]
Giving this a second thought, could this be a misunderstanding of what "possible" means? For overworld locations possible mean it can be checked but not yet reached. So you can see what's on the island from LW, but you can't yet reach it from DW.

**Comment by Dune-jr** [comment]
Thank you for the lengthy explanation, it was just me being an idiot.
Next time I'll find a discord to double check gameplay-related issues with someone as I'm not the brightest guy around with that.

**Comment by RebelusQuo** [comment]
Very well, as long as we figured it out :)
