### ISSUE TITLE
Add the waterfall fairy, 2 chests

### ISSUE THREAD

**Issue by Starfox** [crossproduct42/alttprandohelper#21]
`chests[63] = {
    name: "Waterfall fairy <img src='images/flippers.png' class='mini'>",
    x: "45.4%",
    y: "24.7%",
    isOpened: false,
    isAvailable: function(){
	if(items.flippers)
		return "available";
	return "unavailable";
    }
};`

That's what i added, i hope the coordinates are somewhat accurate

**Comment by RebelusQuo** [comment]
Thank you for your contribution. However, this location is already added to the tracker in the latest version (v5.0.0) and this line of code is not compatible with the current code base. I recommend you to make a fork of this repository in order to keep up to date with development changes.
