### ISSUE TITLE
Scale option for high resolution monitors?

### ISSUE THREAD

**Issue by timeshifter** [crossproduct42/alttprandohelper#22]
Using v4.0, the one thing I actually wanted was a vertical layout, but the one in 5.0 downsizes everything a fairly considerable amount, and it makes for very small click zones on a big 1440p screen. Any chance of getting an option for the vertical layout at the old size?

**Comment by timeshifter** [comment]
ping?

**Comment by RebelusQuo** [comment]
@crossproduct42 and I have discussed this and we want to solve this by providing a general scale option in the launcher instead, implemented through d8400abe17bc83d7e17efb54f165121c0490a356. There were an issue with scrollbars showing in chrome but I've simply hidden them. Edge allows disabling scrollbars on popup windows, so no problems.

If you use something else than Edge or chrome, and you see scrollbars, feel free to reopen the issue.

**Comment by timeshifter** [comment]
Very nice, thanks.
