### ISSUE TITLE
Black screen on sword + TTBK

### ISSUE THREAD

**Issue by godspeedkil** [crossproduct42/alttprandohelper#23]
Wondering if this is repeatable for others. Keysanity tracker goes completely black if I choose a sword and then also activate Thieves' Town Big Key.

**Comment by RebelusQuo** [comment]
On which branch does this happen? I suspect you are looking at "keysanity", and especially the Work In Progress commit, correct? Such commits may not be stable yet.

**Comment by godspeedkil** [comment]
I see, you are correct it is under the keysanity branch. I will close this issue now, then. Thanks!
