### ISSUE TITLE
Spectacle Rock Colouration

### ISSUE THREAD

**Issue by ghost** [crossproduct42/alttprandohelper#24]
Upon getting Gloves Spectacle Rock Cave turns Blue, and should be Green
If you have both Gloves and Mirror, the top of spectacle rock also turns Blue, and should be Green
If you have both Gloves, Hookshot, eastern Death mountain is also Blue instead of Green
If you have the Glove, Hookshot, and Pearl, DW eastern Death Mountain is also Blue instead of green
If you have the flute or Lantern, spectacle rock works properly.

**Comment by RebelusQuo** [comment]
.. while also having lamp or flute?

**Comment by Aestolia** [comment]
Sorry i was updating my comments, see above

**Comment by ghost** [comment]
Oh wait.. i got it never mind

**Comment by ghost** [comment]
it literally just clicked, i'm an idiot, don't mind me nothing to see here!

**Comment by RebelusQuo** [comment]
Yeah, so blue means available if you know how to navigate dark rooms ;)

**Comment by ghost** [comment]
Yeah I know what blue means. it just didn't occur to me that those locations were locked behind the old man

**Comment by RebelusQuo** [comment]
Ah, I see.. Thank for your contribution none the less.

**Comment by ghost** [comment]
Sorry for the trouble, awesome response time though!
